name: flutter_clean_architecture
description: "Flutter Clean Architecture Boilerplate"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Path Provider
  path_provider: ^2.1.2
  provider: ^6.1.1

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.6.7

  # Remote Data Source
  dio: ^5.4.1
  http: ^1.2.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Build Generator
  build_runner: ^2.4.8

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Sqlite Database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Bloc State Management
  flutter_bloc: ^8.1.4

  # For Testing Class
  equatable: ^2.0.5

  # Permission Handler
  permission_handler: ^11.3.0

  # Toast
  toastification: ^1.2.1

  # Logger Interceptor
  pretty_dio_logger: ^1.3.1

  # Image Loader
  flutter_image: ^4.1.11

  # Paging
  infinite_scroll_pagination: ^4.0.0

  # Splash Screen
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/logo_white.png
    - assets/splash/logo_black.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/logo_black.png
  color_dark: "#1E1E1E"
  image_dark: assets/splash/logo_white.png

  android_12:
    image: assets/splash/logo_black.png
    color: "#FFFFFF"
    image_dark: assets/splash/logo_white.png
    color_dark: "#1E1E1E"

  android: true
  ios: true
  web: true