name: flutter_clean_architecture
description: "Flutter Clean Architecture Boilerplate"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Path Provider
  path_provider: ^2.1.2
  provider: ^6.1.1

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Dependency Injection
  get_it: ^7.6.7

  # Remote Data Source
  dio: ^5.4.1
  http: ^1.2.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Build Generator
  build_runner: ^2.4.8

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Sqlite Database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Bloc State Management
  flutter_bloc: ^8.1.4

  # For Testing Class
  equatable: ^2.0.5

  # Permission Handler
  permission_handler: ^11.3.0

  # Toast
  toastification: ^1.2.1

  # Logger Interceptor
  pretty_dio_logger: ^1.3.1

  # Image Loader
  flutter_image: ^4.1.11

  # Paging
  infinite_scroll_pagination: ^4.0.0

  # Splash Screen
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_white.png
    - assets/images/logo_black.png

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/poppins/Poppins-Regular.otf
         weight: 400
       - asset: assets/fonts/poppins/Poppins-Italic.otf
         weight: 400
         style: italic
       - asset: assets/fonts/poppins/Poppins-Medium.otf
         weight: 500
       - asset: assets/fonts/poppins/Poppins-SemiBold.otf
         weight: 600
       - asset: assets/fonts/poppins/Poppins-Bold.otf
         weight: 700
       - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
         weight: 800
   - family: Playfair Display
     fonts:
       - asset: assets/fonts/playfair/PlayfairDisplay-Regular.ttf
         weight: 400
       - asset: assets/fonts/playfair/PlayfairDisplay-Italic.ttf
         weight: 400
         style: italic
       - asset: assets/fonts/playfair/PlayfairDisplay-Medium.ttf
         weight: 500
       - asset: assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
         weight: 700
       - asset: assets/fonts/playfair/PlayfairDisplay-ExtraBold.ttf
         weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_black.png
  color_dark: "#1E1E1E"
  image_dark: assets/images/logo_white.png
  android_12:
    image: assets/images/logo_black.png
    color: "#FFFFFF"
    image_dark: assets/images/logo_white.png
    color_dark: "#1E1E1E"
  android: true
  ios: true
  web: true