// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYjpzhsd5e7wD4N-ztyQJgliWvFoM36I',
    appId: '1:76615585221:web:a3d43d95ef1c5266534fac',
    messagingSenderId: '76615585221',
    projectId: 'fluttercleanarchitecture-244ac',
    authDomain: 'fluttercleanarchitecture-244ac.firebaseapp.com',
    storageBucket: 'fluttercleanarchitecture-244ac.appspot.com',
    measurementId: 'G-5W9YGG0Y5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYnCx6Z5LlLT3km0jbmJJdYG_9lemeMQ',
    appId: '1:76615585221:android:ec174cf6bad6cca7534fac',
    messagingSenderId: '76615585221',
    projectId: 'fluttercleanarchitecture-244ac',
    storageBucket: 'fluttercleanarchitecture-244ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRoBID32FOKNK8JuKWldZZACCH9mQmHE',
    appId: '1:76615585221:ios:c81be2a070c2a34a534fac',
    messagingSenderId: '76615585221',
    projectId: 'fluttercleanarchitecture-244ac',
    storageBucket: 'fluttercleanarchitecture-244ac.appspot.com',
    iosBundleId: 'com.flutter.cleanarch.flutterCleanArchitecture',
  );
}
